/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mario;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *hola jenny!
 * @author Jenny
 */
public class Mostrar extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar
     */
    static private Pila pila;
    static private ListaDoble datos;
    
    public Mostrar(ListaDoble jeny) {
        this.datos = jeny;
        //vamos a llenar la pila, recorriendo la lista doble
        this.pila = new Pila();
        recorrerListaDoble(pila);
        //recorrerpop(pila);
        initComponents();
   
        //SI HAGO ESTO ES COMO QUE SI ESTUVIERA HACIENDO UNA NUEVA LISTA
    //datos = new ListaDoble();
 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccionar tipo de ordenamiento para mostrar datos:");

        jButton1.setText("Cola");
        jButton1.setActionCommand("Pila");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cola");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     //L HZ FR
        String mostrar="";
        ListaDoble ja = this.datos;
        ObtenerDatos lista;
        Nodo elemento = ja.Inicio;
        while (elemento != null){
           String nombre = elemento.datos.getNombre();
           ImageIcon imagen = elemento.datos.getImagen();
           mostrar = mostrar +"Nombre objetos:   "+nombre+"Imagen objeto:"+ imagen;
           //System.out.println("orden:   " );
           JOptionPane.showMessageDialog(rootPane, imagen, nombre, WIDTH);
          // MOSTRAR.add(nombre, this);
          elemento = elemento.siguiente;   
          
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    //============================================
    //L H FR
    public void recorrerListaDoble(Pila obj)
    {
        ListaDoble ja = this.datos;
        //ObtenerDatos lista;
        Nodo elemento = ja.Inicio;
        while (elemento != null){           
          ObtenerDatos od = elemento.getDatos();
         
          obj.Push(od);
          elemento = elemento.siguiente;           
        }
        this.pila = obj;
    }
    
    
    
    public void recorrerpop(Pila pop)
    {
     ListaDoble ja = this.datos;
        //ObtenerDatos lista;
        Nodo elemento = ja.Inicio;
        while (elemento != null){           
          ObtenerDatos od = elemento.getDatos();
          //String nom = elemento.datos.getNombre();
          //ImageIcon img = elemento.datos.getImagen();
          pop.Pop(od);
          ImageIcon amagg = od.getImagen();
          String nomm = od.getNombre();
          JOptionPane.showMessageDialog(rootPane, amagg, nomm, WIDTH);
          elemento = elemento.anterior;           
    }  //this.pila = pop;
    }

    //=============================================
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //metodo de mostrar la pila
        //mandar a recorrer la pila con el while
   recorrerpop(pila);
   
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar(datos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
